### ISSUE TITLE
Annotation versions for other species?

### ISSUE THREAD

**Issue by nikostr** [hhy18/Annotation-files-of-Stellera-chamaejasme#1]
Hi! Thank you for this resource! :) What exact annotation versions from the other species were used in creating and analyzing this annotation? The paper mentions Arabidopsis thaliana, Prunus persica, Vitis vinifera, Punica granatum and Nyssa sinensis, as well as Oryza sativa (assembly Build 4.0), Calotropis gigantea, Eucalyptus grandis, Medicago truncatula, and Aquilaria sinensis but I can't seem to find exact versions of these annotations, nor am I finding references to publications of the annotations used. Where can I find this information? :)

**Comment by hhy18** [comment]
I'm sorry, I didn't include genome version information in my article, but it seems that the latest versions of these species are used, which you can download in Phytozome v13.
